name: Тест публикации файлов в S3
description: простой экшен для тестирования импорта
runs:
  using: "composite"
  # volumes:
  #   - /root/.aws:/root/.aws
  steps:
    - name: получение списка файлов
      run: aws --version